### ISSUE TITLE
Unclosed AsyncClient warning

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [supabase-community/postgrest-py#83]
I am getting the warning
```
/opt/virtualenvs/python3/lib/python3.8/site-packages/httpx/_client.py:2012: UserWarning: Unclosed <httpx.AsyncClient object at 0x7fbff4298310>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
  warnings.warn(
```
every time I execute a command. I installed postgrest-py via poetry.

**Comment by anand2312** [comment]
How are you running this? The warning is because the underlying `httpx.AsyncClient` isn't being closed at the end; an easy way to ensure that it's closed is to use `AsyncPostgrestClient` with a context manager:
```py
async with AsyncPostgrestClient(url) as client:
    # do queries here
    # the connection is closed when the 'with' block ends
```
Otherwise, you can explicitly call the `aclose` method at the end:
https://github.com/supabase-community/postgrest-py/blob/34fd1bda6893782a955340e39bcdba6633034a69/postgrest_py/_async/client.py#L56
